################################################################################
# yandex2nodered
################################################################################
# docker stack deploy yandex2nodered --compose-file docker-compose-yandex2nodered.yml
# docker-compose -f docker-compose-yandex2nodered.yml -p yandex2mqtt up
################################################################################
version: "2"

services:
  node-red:
    image: bawdiest/node-red-docker
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - /media/docker/node-red:/data

  yandex2mqtt:
    image: bawdiest/yandex2mqtt
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1800:1800"
    networks:
      - node-red-net
    volumes:
      - /media/docker/yandex2mqtt/conf.js:/usr/src/yandex2mqtt/conf.js

  mosquitto:
    image: eclipse-mosquitto
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - node-red-net

networks:
  node-red-net:
